In [4]:
import requests
import pandas as pd
import json
from openpyxl import load_workbook
from openpyxl.utils import get_column_letter
from datetime import datetime

In [5]:
params = {
# 'serviceName':'Azure AI Search',
'productName':'Azure AI Search',
'location':'US West',
'currencyCode':"USD",
"type": "Consumption"
}

clean_url = "https://prices.azure.com/api/retail/prices"

timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
file_name = f"costs_summary_{timestamp}"
excel_file_name = f"{file_name}.xlsx"

filters = []
for key, value in params.items():
    if value != "":
        filters.append(f"{key} eq '{value}'")

new_url = clean_url + '?$filter=' + ' and '.join(filters)
print(new_url)

response_text = requests.get(new_url).text

https://prices.azure.com/api/retail/prices?$filter=productName eq 'Azure AI Search' and location eq 'US West' and currencyCode eq 'USD' and type eq 'Consumption'

In [9]:
with open("output.json", "w", encoding="utf-8") as f:

    f.write(response_text)

In [3]:
data = json.loads(response_text)
df = pd.DataFrame(data["Items"])

df_values = df[['retailPrice', 'productName', 'meterName', 'skuName', 'armSkuName', 'unitOfMeasure',]]
df_values = df_values.sort_values(by=['productName', 'skuName', 'unitOfMeasure'], ascending=True)
df_values.to_excel(excel_file_name, index=False)

wb = load_workbook(excel_file_name)
ws = wb.active
ws.auto_filter.ref = ws.dimensions
ws.freeze_panes = "A2"

for column_cells in ws.columns:
    max_length = 0
    column_letter = column_cells[0].column_letter

    for cell in column_cells:
        if cell.value is not None:
            max_length = max(max_length, len(str(cell.value)))

    ws.column_dimensions[column_letter].width = max_length + 0

wb.save(excel_file_name)

with open(f"{file_name}.json", "w", encoding="utf-8") as f:
    f.write(response_text)

In [4]:
df

,currencyCode,tierMinimumUnits,retailPrice,unitPrice,armRegionName,location,effectiveStartDate,meterId,meterName,productId,skuId,productName,skuName,serviceName,serviceId,serviceFamily,unitOfMeasure,type,isPrimaryMeterRegion,armSkuName
0,USD,0.0,0.000000,0.000000,westus,US West,2026-01-01T00:00:00Z,0a0fc5d3-e457-5180-bead-da40cd1ac2c4,Free Agentic Retrieval Medium Reasoning Tokens,DZH318Z0BQKZ,DZH318Z0BQKZ/02VV,Azure AI Search,Free Agentic Retrieval Medium Reasoning,Azure Cognitive Search,DZH318X5DGJB,Web,1K,Consumption,True,Free Agentic Retrieval Medium Reasoning
1,USD,0.0,1.344000,1.344000,westus,US West,2015-05-01T00:00:00Z,99f367c4-70a5-4595-a7f0-fb38478c9cff,Standard S2 Unit,DZH318Z0BQKZ,DZH318Z0BQKZ/003X,Azure AI Search,Standard S2,Azure Cognitive Search,DZH318X5DGJB,Web,1 Hour,Consumption,False,
2,USD,0.0,0.000000,0.000000,westus,US West,2015-05-01T00:00:00Z,ab5b133b-d9da-4c2d-be66-0c3d70a8e69c,Free Unit,DZH318Z0BQKZ,DZH318Z0BQKZ/0035,Azure AI Search,Free,Azure Cognitive Search,DZH318X5DGJB,Web,1 Hour,Consumption,False,
3,USD,0.0,16.120000,16.120000,westus,US West,2021-04-01T00:00:00Z,c6136a6b-7950-5939-8fc4-27fc1a251c4e,Semantic Ranker Unit,DZH318Z0BQKZ,DZH318Z0BQKZ/00QV,Azure AI Search,Semantic Ranker,Azure Cognitive Search,DZH318X5DGJB,Web,1/Day,Consumption,False,
4,USD,0.0,1.000000,1.000000,westus,US West,2023-11-15T00:00:00Z,4620ac9d-57be-5568-848e-60ea9f1014db,Semantic Ranker queries,DZH318Z0BQKZ,DZH318Z0BQKZ/00QV,Azure AI Search,Semantic Ranker,Azure Cognitive Search,DZH318X5DGJB,Web,1K,Consumption,True,
5,USD,0.0,2.688000,2.688000,westus,US West,2016-12-01T00:00:00Z,a329232f-c89b-433f-abba-2fc810762aaf,Standard S3 Unit,DZH318Z0BQKZ,DZH318Z0BQKZ/001C,Azure AI Search,Standard S3,Azure Cognitive Search,DZH318X5DGJB,Web,1 Hour,Consumption,False,
6,USD,0.0,2.000000,2.000000,westus,US West,2021-04-01T00:00:00Z,48ca7cce-7497-5baf-9fb3-da393583aade,Semantic Ranker Overage Queries,DZH318Z0BQKZ,DZH318Z0BQKZ/00QV,Azure AI Search,Semantic Ranker,Azure Cognitive Search,DZH318X5DGJB,Web,1K,Consumption,False,
7,USD,0.0,7.677000,7.677000,westus,US West,2019-09-01T00:00:00Z,4ae8fbb9-0468-41f7-9ca8-45b1cd1d4774,Storage Optimized L2 Unit,DZH318Z0BQKZ,DZH318Z0BQKZ/008H,Azure AI Search,Storage Optimized L2,Azure Cognitive Search,DZH318X5DGJB,Web,1 Hour,Consumption,False,
8,USD,0.0,0.000000,0.000000,westus,US West,2026-05-01T00:00:00Z,775dc073-1b3d-52fd-8b30-ddb8920bb28b,Free Agentic Retrieval Minimum Reasoning Tokens,DZH318Z0BQKZ,DZH318Z0BQKZ/02W1,Azure AI Search,Free Agentic Retrieval Minimum Reasoning,Azure Cognitive Search,DZH318X5DGJB,Web,1K,Consumption,True,Free Agentic Retrieval Minimum Reasoning
9,USD,0.0,0.336000,0.336000,westus,US West,2015-05-01T00:00:00Z,412d6928-652a-44ec-8bbb-d1dea652b7a6,Standard S1 Unit,DZH318Z0BQKZ,DZH318Z0BQKZ/002L,Azure AI Search,Standard S1,Azure Cognitive Search,DZH318X5DGJB,Web,1 Hour,Consumption,False,
10,USD,0.0,0.101000,0.101000,westus,US West,2016-08-01T00:00:00Z,0c873ca2-4113-4997-8cf6-ad5df5775599,Basic Unit,DZH318Z0BQKZ,DZH318Z0BQKZ/002S,Azure AI Search,Basic,Azure Cognitive Search,DZH318X5DGJB,Web,1 Hour,Consumption,False,
11,USD,0.0,0.000000,0.000000,westus,US West,2026-01-01T00:00:00Z,a4df4280-b962-55cb-a308-3d0cb41f9ac1,Free queries,DZH318Z0BQKZ,DZH318Z0BQKZ/0035,Azure AI Search,Free,Azure Cognitive Search,DZH318X5DGJB,Web,1K,Consumption,True,
12,USD,0.0,1.000000,1.000000,westus,US West,2021-05-01T00:00:00Z,e8fc8ffa-48c2-50f2-9dda-27d3c9ac27e5,Custom Entity Skills Text Records,DZH318Z0BQKZ,DZH318Z0BQKZ/00T6,Azure AI Search,Custom Entity Skills,Azure Cognitive Search,DZH318X5DGJB,Web,1K,Consumption,False,
13,USD,10000.0,0.250000,0.250000,westus,US West,2021-05-01T00:00:00Z,e8fc8ffa-48c2-50f2-9dda-27d3c9ac27e5,Custom Entity Skills Text Records,DZH318Z0BQKZ,DZH318Z0BQKZ/00T6,Azure AI Search,Custom Entity Skills,Azure Cognitive Search,DZH318X5DGJB,Web,1K,Consumption,False,
14,USD,2500.0,0.300000,0.300000,westus,US West,2021-05-01T00:00:00Z,e8fc8ffa-48c2-50f2-9dda-27d3c9ac27e5,Custom Entity Skills Text Records,DZH318Z0BQKZ,DZH318Z0BQKZ/00T6,Azure AI Search,Custom Entity Skills,Azure Cognitive Search,DZH318X5DGJB,Web,1K,Consumption,False,
15,USD,500.0,0.750000,0.750000,westus,US West,2021-05-01T00:00:00Z,e8fc8ffa-48c2-50f2-9dda-27d3c9ac27e5,Custom Entity Skills Text Records,DZH318Z0BQKZ,DZH318Z0BQKZ/00T6,Azure AI Search,Custom Entity Skills,Azure Cognitive Search,DZH318X5DGJB,Web,1K,Consumption,False,
16,USD,0.0,3.839000,3.839000,westus,US West,2019-09-01T00:00:00Z,e4878469-1253-4f18-8f83-56e41777c3fb,Storage Optimized L1 Unit,DZH318Z0BQKZ,DZH318Z0BQKZ/0087,Azure AI Search,Storage Optimized L1,Azure Cognitive Search,DZH318X5DGJB,Web,1 Hour,Consumption,False,
17,USD,0.0,0.000100,0.000100,westus,US West,2026-01-01T00:00:00Z,c4ceef70-c7e7-5fae-8803-1acee2e821a8,Agentic Retrieval Medium Reasoning Tokens,DZH318Z0BQKZ,DZH318Z0BQKZ/0263,Azure AI Search,Agentic Retrieval Medium Reasoning,Azure Cognitive Search,DZH318X5DGJB,Web,1K,Consumption,True,Semantic Classifier
18,USD,0.0,0.000022,0.000022,westus,US West,2025-07-01T00:00:00Z,c8b03be5-ac44-5c41-bb5e-a02d4c5918c9,Agentic Retrieval Low Reasoning Tokens,DZH318Z0BQKZ,DZH318Z0BQKZ/01HD,Azure AI Search,Agentic Retrieval Low Reasoning,Azure Cognitive Search,DZH318X5DGJB,Web,1K,Consumption,True,Knowledge Retrieval
19,USD,0.0,0.000022,0.000022,westus,US West,2026-05-01T00:00:00Z,cfcae972-7d98-5484-b17e-deb451611f57,Agentic Retrieval Minimum Reasoning Tokens,DZH318Z0BQKZ,DZH318Z0BQKZ/02VW,Azure AI Search,Agentic Retrieval Minimum Reasoning,Azure Cognitive Search,DZH318X5DGJB,Web,1K,Consumption,True,Agentic Retrieval Minimum Reasoning
20,USD,0.0,1.000000,1.000000,westus,US West,2019-07-01T00:00:00Z,036fcc20-399f-4822-b568-d96c62899d1d,Document Cracking Image Extraction,DZH318Z0BQKZ,DZH318Z0BQKZ/0072,Azure AI Search,Document Cracking,Azure Cognitive Search,DZH318X5DGJB,Web,1K,Consumption,False,
21,USD,1000.0,0.800000,0.800000,westus,US West,2019-07-01T00:00:00Z,036fcc20-399f-4822-b568-d96c62899d1d,Document Cracking Image Extraction,DZH318Z0BQKZ,DZH318Z0BQKZ/0072,Azure AI Search,Document Cracking,Azure Cognitive Search,DZH318X5DGJB,Web,1K,Consumption,False,
22,USD,5000.0,0.650000,0.650000,westus,US West,2019-07-01T00:00:00Z,036fcc20-399f-4822-b568-d96c62899d1d,Document Cracking Image Extraction,DZH318Z0BQKZ,DZH318Z0BQKZ/0072,Azure AI Search,Document Cracking,Azure Cognitive Search,DZH318X5DGJB,Web,1K,Consumption,False,
23,USD,0.0,0.000000,0.000000,westus,US West,2026-01-01T00:00:00Z,f2c46ebd-bfd8-541f-84ac-8bbfff954b1d,Free Agentic Retrieval Low Reasoning Tokens,DZH318Z0BQKZ,DZH318Z0BQKZ/02VZ,Azure AI Search,Free Agentic Retrieval Low Reasoning,Azure Cognitive Search,DZH318X5DGJB,Web,1K,Consumption,True,Free Agentic Retrieval Low Reasoning

In [17]:
df_values.head(10)
# df_values.count()

,retailPrice,productName,meterName,skuName,armSkuName,unitOfMeasure
18,0.000022,Azure AI Search,Agentic Retrieval Low Reasoning Tokens,Agentic Retrieval Low Reasoning,Knowledge Retrieval,1K
17,0.000100,Azure AI Search,Agentic Retrieval Medium Reasoning Tokens,Agentic Retrieval Medium Reasoning,Semantic Classifier,1K
19,0.000022,Azure AI Search,Agentic Retrieval Minimum Reasoning Tokens,Agentic Retrieval Minimum Reasoning,Agentic Retrieval Minimum Reasoning,1K
10,0.101000,Azure AI Search,Basic Unit,Basic,,1 Hour
12,1.000000,Azure AI Search,Custom Entity Skills Text Records,Custom Entity Skills,,1K
13,0.250000,Azure AI Search,Custom Entity Skills Text Records,Custom Entity Skills,,1K
14,0.300000,Azure AI Search,Custom Entity Skills Text Records,Custom Entity Skills,,1K
15,0.750000,Azure AI Search,Custom Entity Skills Text Records,Custom Entity Skills,,1K
20,1.000000,Azure AI Search,Document Cracking Image Extraction,Document Cracking,,1K
21,0.800000,Azure AI Search,Document Cracking Image Extraction,Document Cracking,,1K

In [34]:
# new_url = "https://prices.azure.com/api/retail/prices?$filter=serviceName eq 'Azure Cosmos DB' and location eq 'US West' and currencyCode eq 'USD'"

In [11]:
import json
import os
import requests
from datetime import datetime

params = {
    "location": "US West",
    "currencyCode": "USD"
}

clean_url = "https://prices.azure.com/api/retail/prices"

timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
output_dir = f"azure_prices_items_{timestamp}"

os.makedirs(output_dir, exist_ok=True)

filters = []
for key, value in params.items():
    if value:
        filters.append(f"{key} eq '{value}'")

url = clean_url + "?$filter=" + " and ".join(filters)

page = 1
total_records = 0

while url:
    print(f"=== Strona {page} ===")

    response = requests.get(url, timeout=60)
    response.raise_for_status()

    data = response.json()
    items = data.get("Items", [])

    print(f"Rekordów na stronie: {len(items)}")

    for item_index, item in enumerate(items, start=1):
        total_records += 1

        file_name = f"item_{total_records:08d}_page_{page:04d}_row_{item_index:04d}.json"
        file_path = os.path.join(output_dir, file_name)

        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(item, f, indent=2, ensure_ascii=False)

    url = data.get("NextPageLink")

    print(f"Łącznie zapisano elementów: {total_records}")

    if url:
        print("Kolejna strona znaleziona")
    else:
        print("Koniec paginacji")

    print()
    page += 1

print("=" * 60)
print("Zakończono")
print(f"Stron: {page - 1}")
print(f"Elementów zapisanych jako osobne JSON-y: {total_records}")
print(f"Katalog: {output_dir}")

=== Strona 1 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 1000
Kolejna strona znaleziona

=== Strona 2 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 2000
Kolejna strona znaleziona

=== Strona 3 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 3000
Kolejna strona znaleziona

=== Strona 4 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 4000
Kolejna strona znaleziona

=== Strona 5 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 5000
Kolejna strona znaleziona

=== Strona 6 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 6000
Kolejna strona znaleziona

=== Strona 7 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 7000
Kolejna strona znaleziona

=== Strona 8 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 8000
Kolejna strona znaleziona

=== Strona 9 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 9000
Kolejna strona znaleziona

=== Strona 10 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 10000
Kolejna strona znaleziona

=== Strona 11 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 11000
Kolejna strona znaleziona

=== Strona 12 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 12000
Kolejna strona znaleziona

=== Strona 13 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 13000
Kolejna strona znaleziona

=== Strona 14 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 14000
Kolejna strona znaleziona

=== Strona 15 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 15000
Kolejna strona znaleziona

=== Strona 16 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 16000
Kolejna strona znaleziona

=== Strona 17 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 17000
Kolejna strona znaleziona

=== Strona 18 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 18000
Kolejna strona znaleziona

=== Strona 19 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 19000
Kolejna strona znaleziona

=== Strona 20 ===
Rekordów na stronie: 1000
Łącznie zapisano elementów: 20000
Kolejna strona znaleziona

=== Strona 21 ===
Rekordów na stronie: 683
Łącznie zapisano elementów: 20683
Koniec paginacji

============================================================
Zakończono
Stron: 21
Elementów zapisanych jako osobne JSON-y: 20683
Katalog: azure_prices_items_20260603165532

In [4]:
from pathlib import Path
import polars as pl

folder = Path("azure_prices_items_20260603165532")
files = sorted(folder.glob("*.json"))

len(files)

df = pl.concat(
    [pl.read_json(str(file)) for file in files],
    how="diagonal_relaxed",
)

df.shape

(20683, 22)

In [5]:
df

shape: (20_683, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ currencyC ┆ tierMinim ┆ retailPri ┆ unitPrice ┆ … ┆ isPrimary ┆ armSkuNam ┆ reservati ┆ effectiv │
│ ode       ┆ umUnits   ┆ ce        ┆ ---       ┆   ┆ MeterRegi ┆ e         ┆ onTerm    ┆ eEndDate │
│ ---       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ on        ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ f64       ┆ f64       ┆           ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ bool      ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ USD       ┆ 0.0       ┆ 0.034927  ┆ 0.034927  ┆ … ┆ true      ┆ Standard_ ┆ null      ┆ null     │
│           ┆           ┆           ┆           ┆   ┆           ┆ E2bds_v5  ┆           ┆          │
│ USD       ┆ 0.0       ┆ 0.04428   ┆ 0.04428   ┆ … ┆ true      ┆ Standard_ ┆ null      ┆ null     │
│           ┆           ┆           ┆           ┆   ┆           ┆ B2pls_v2  ┆           ┆          │
│ USD       ┆ 0.0       ┆ 0.036     ┆ 0.036     ┆ … ┆ true      ┆ Standard_ ┆ null      ┆ null     │
│           ┆           ┆           ┆           ┆   ┆           ┆ B2pls_v2  ┆           ┆          │
│ USD       ┆ 0.0       ┆ 0.167439  ┆ 0.167439  ┆ … ┆ true      ┆ SQLDB_GP_ ┆ null      ┆ null     │
│           ┆           ┆           ┆           ┆   ┆           ┆ Compute_G ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ en4_1     ┆           ┆          │
│ USD       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ false     ┆           ┆ null      ┆ null     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ USD       ┆ 0.0       ┆ 0.0101    ┆ 0.0101    ┆ … ┆ true      ┆ Cold      ┆ null      ┆ null     │
│ USD       ┆ 0.0       ┆ 0.146     ┆ 0.146     ┆ … ┆ true      ┆ AzureDB_M ┆ null      ┆ null     │
│           ┆           ┆           ┆           ┆   ┆           ┆ ySQL_Flex ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ible_Serv ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ er_…      ┆           ┆          │
│ USD       ┆ 0.0       ┆ 766.0     ┆ 766.0     ┆ … ┆ true      ┆ AzureDB_M ┆ 1 Year    ┆ null     │
│           ┆           ┆           ┆           ┆   ┆           ┆ ySQL_Flex ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ible_Serv ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ er_…      ┆           ┆          │
│ USD       ┆ 0.0       ┆ 1530.0    ┆ 1530.0    ┆ … ┆ true      ┆ AzureDB_M ┆ 3 Years   ┆ null     │
│           ┆           ┆           ┆           ┆   ┆           ┆ ySQL_Flex ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ible_Serv ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ er_…      ┆           ┆          │
│ USD       ┆ 0.0       ┆ 0.525941  ┆ 0.525941  ┆ … ┆ true      ┆ Standard_ ┆ null      ┆ null     │
│           ┆           ┆           ┆           ┆   ┆           ┆ FX16mds_v ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘